version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:123@db:5432/matan_crm?schema=public
    command: sh -c "npx prisma generate && npm start"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    container_name: crm-postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: matan_crm
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
